pipeline:
  name: bugbash-07-naman
  identifier: bugbash07naman
  projectIdentifier: proj
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: sg
        identifier: sg
        description: ""
        type: Approval
        spec:
          execution:
            steps:
              - step:
                  type: ShellScript
                  name: qwsdefr
                  identifier: qwsdefr
                  spec:
                    shell: Bash
                    onDelegate: true
                    source:
                      type: Inline
                      spec:
                        script: echo naman
                    environmentVariables: []
                    outputVariables: []
                  timeout: 10m
        tags: {}
    - stage:
        name: dfg
        identifier: dfg
        description: ""
        type: Approval
        spec:
          execution:
            steps:
              - step:
                  type: CustomApproval
                  name: df
                  identifier: df
                  spec:
                    rejectionCriteria:
                      type: KeyValues
                      spec:
                        matchAnyCondition: true
                        conditions: []
                    approvalCriteria:
                      type: KeyValues
                      spec:
                        matchAnyCondition: true
                        conditions:
                          - key: VAR1
                            operator: equals
                            value: Sd
                    scriptTimeout: 10m
                    retryInterval: 10s
                    shell: Bash
                    onDelegate: true
                    source:
                      type: Inline
                      spec:
                        script: |-
                          echo naman
                          export VAR1 = "Sd"
                    environmentVariables: []
                    outputVariables:
                      - name: VAR1
                        type: String
                        value: Sd
                  timeout: 1d
        tags: {}
